package com.heima.express.crm.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2020-01-06T01:03:18.537+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebService(targetNamespace = "http://service.crm.express/", name = "CustomerService")
//@XmlSeeAlso({ObjectFactory.class})
public interface CustomerService {

    @WebMethod
    @RequestWrapper(localName = "addAssCustomers", targetNamespace = "http://service.crm.express/", className = "com.heima.express.crm.client.AddAssCustomers")
    @ResponseWrapper(localName = "addAssCustomersResponse", targetNamespace = "http://service.crm.express/", className = "com.heima.express.crm.client.AddAssCustomersResponse")
    public void addAssCustomers(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.Integer> arg1
    );

    @WebMethod
    @RequestWrapper(localName = "findCustomersByDzoneid", targetNamespace = "http://service.crm.express/", className = "com.heima.express.crm.client.FindCustomersByDzoneid")
    @ResponseWrapper(localName = "findCustomersByDzoneidResponse", targetNamespace = "http://service.crm.express/", className = "com.heima.express.crm.client.FindCustomersByDzoneidResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.heima.express.crm.client.TCustomer> findCustomersByDzoneid(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findCustomersNoAss", targetNamespace = "http://service.crm.express/", className = "com.heima.express.crm.client.FindCustomersNoAss")
    @ResponseWrapper(localName = "findCustomersNoAssResponse", targetNamespace = "http://service.crm.express/", className = "com.heima.express.crm.client.FindCustomersNoAssResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.heima.express.crm.client.TCustomer> findCustomersNoAss();
}
