package com.heima.express.manage.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.heima.express.common.DataGridResult;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2020-01-09T17:54:51.173+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebService(targetNamespace = "http://service.manage.express.heima.com/", name = "QpService")
//@XmlSeeAlso({ObjectFactory.class})
public interface QpService {

    @WebMethod
    @RequestWrapper(localName = "findAllStaff", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindAllStaff")
    @ResponseWrapper(localName = "findAllStaffResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindAllStaffResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.heima.express.manage.client.BcStaff> findAllStaff();

    @WebMethod
    @RequestWrapper(localName = "updateForAss", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.UpdateForAss")
    @ResponseWrapper(localName = "updateForAssResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.UpdateForAssResponse")
    public void updateForAss(
        @WebParam(name = "arg0", targetNamespace = "")
        com.heima.express.manage.client.QpNoticebill arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findAllNoAss", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindAllNoAss")
    @ResponseWrapper(localName = "findAllNoAssResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindAllNoAssResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DataGridResult findAllNoAss(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "addQp", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.AddQp")
    @ResponseWrapper(localName = "addQpResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.AddQpResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.heima.express.manage.client.BcStaff addQp(
        @WebParam(name = "arg0", targetNamespace = "")
        com.heima.express.manage.client.QpNoticebill arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception;
}
