package com.heima.express.manage.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2020-01-06T22:04:35.946+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebService(targetNamespace = "http://service.manage.express.heima.com/", name = "RegionService")
//@XmlSeeAlso({ObjectFactory.class})
public interface RegionService {

    @WebMethod
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.heima.express.manage.client.BcRegion> findAll();

    @WebMethod
    @RequestWrapper(localName = "addRegions", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.AddRegions")
    @ResponseWrapper(localName = "addRegionsResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.AddRegionsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int addRegions(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.heima.express.manage.client.BcRegion> arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findRegionByKey", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindRegionByKey")
    @ResponseWrapper(localName = "findRegionByKeyResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindRegionByKeyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.heima.express.manage.client.BcRegion> findRegionByKey(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
