package com.heima.express.manage.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.heima.express.common.AppResult;
import com.heima.express.common.DataGridResult;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2020-01-06T22:04:48.209+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebService(targetNamespace = "http://service.manage.express.heima.com/", name = "RoleService")
//@XmlSeeAlso({ObjectFactory.class})
public interface RoleService {

    @WebMethod
    @RequestWrapper(localName = "findRolesByInput", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindRolesByInput")
    @ResponseWrapper(localName = "findRolesByInputResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindRolesByInputResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DataGridResult findRolesByInput(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.Integer arg2
    );

    @WebMethod
    @RequestWrapper(localName = "findAuthorityTextByRoleid", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindAuthorityTextByRoleid")
    @ResponseWrapper(localName = "findAuthorityTextByRoleidResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindAuthorityTextByRoleidResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> findAuthorityTextByRoleid(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebMethod
    @RequestWrapper(localName = "delRolesByRoleids", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.DelRolesByRoleids")
    @ResponseWrapper(localName = "delRolesByRoleidsResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.DelRolesByRoleidsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int delRolesByRoleids(
        @WebParam(name = "arg0", targetNamespace = "")
        int[] rolesid
    );

    @WebMethod
    @RequestWrapper(localName = "updRole", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.UpdRole")
    @ResponseWrapper(localName = "updRoleResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.UpdRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppResult updRole(
        @WebParam(name = "arg0", targetNamespace = "")
        com.heima.express.manage.client.Role arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addRole", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.AddRole")
    @ResponseWrapper(localName = "addRoleResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.AddRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppResult addRole(
        @WebParam(name = "arg0", targetNamespace = "")
        com.heima.express.manage.client.Role arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findRoleById", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindRoleById")
    @ResponseWrapper(localName = "findRoleByIdResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindRoleByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.heima.express.manage.client.Role findRoleById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findAllRole", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindAllRole")
    @ResponseWrapper(localName = "findAllRoleResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindAllRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DataGridResult findAllRole(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );

    @WebMethod
    @RequestWrapper(localName = "findAllRoles", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindAllRoles")
    @ResponseWrapper(localName = "findAllRolesResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindAllRolesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.heima.express.manage.client.Role> findAllRoles();

    @WebMethod
    @RequestWrapper(localName = "findAuthorityByRoleid", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindAuthorityByRoleid")
    @ResponseWrapper(localName = "findAuthorityByRoleidResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindAuthorityByRoleidResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> findAuthorityByRoleid(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );
}
