package com.heima.express.manage.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2020-01-06T22:04:52.791+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebService(targetNamespace = "http://service.manage.express.heima.com/", name = "RrightService")
//@XmlSeeAlso({ObjectFactory.class})
public interface RrightService {

    @WebMethod
    @RequestWrapper(localName = "deleteFolderRight", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.DeleteFolderRight")
    @ResponseWrapper(localName = "deleteFolderRightResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.DeleteFolderRightResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int deleteFolderRight(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findCheckResultByrighttext", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindCheckResultByrighttext")
    @ResponseWrapper(localName = "findCheckResultByrighttextResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindCheckResultByrighttextResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean findCheckResultByrighttext(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findRrightForMenu", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindRrightForMenu")
    @ResponseWrapper(localName = "findRrightForMenuResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindRrightForMenuResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.heima.express.manage.client.Rright> findRrightForMenu(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );

    @WebMethod
    @RequestWrapper(localName = "updaterightdnd", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.Updaterightdnd")
    @ResponseWrapper(localName = "updaterightdndResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.UpdaterightdndResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int updaterightdnd(
        @WebParam(name = "arg0", targetNamespace = "")
        com.heima.express.manage.client.Rright arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addRright", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.AddRright")
    @ResponseWrapper(localName = "addRrightResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.AddRrightResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int addRright(
        @WebParam(name = "arg0", targetNamespace = "")
        com.heima.express.manage.client.Rright arg0
    );

    @WebMethod
    @RequestWrapper(localName = "updateRright", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.UpdateRright")
    @ResponseWrapper(localName = "updateRrightResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.UpdateRrightResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int updateRright(
        @WebParam(name = "arg0", targetNamespace = "")
        com.heima.express.manage.client.Rright arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findRrightsForCurd", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindRrightsForCurd")
    @ResponseWrapper(localName = "findRrightsForCurdResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindRrightsForCurdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.heima.express.manage.client.Rright> findRrightsForCurd(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );

    @WebMethod
    @RequestWrapper(localName = "deleteRright", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.DeleteRright")
    @ResponseWrapper(localName = "deleteRrightResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.DeleteRrightResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int deleteRright(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );
}
