package com.heima.express.manage.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.heima.express.common.DataGridResult;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2020-01-06T22:05:04.248+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebService(targetNamespace = "http://service.manage.express.heima.com/", name = "UsersService")
//@XmlSeeAlso({ObjectFactory.class})
public interface UsersService {

    @WebMethod
    @RequestWrapper(localName = "findUserdByName", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindUserdByName")
    @ResponseWrapper(localName = "findUserdByNameResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindUserdByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.heima.express.manage.client.Users> findUserdByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "delusersbycheck", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.Delusersbycheck")
    @ResponseWrapper(localName = "delusersbycheckResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.DelusersbycheckResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int delusersbycheck(
        @WebParam(name = "arg0", targetNamespace = "")
        int[] uids
    );

    @WebMethod
    @RequestWrapper(localName = "findUserForLogin", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindUserForLogin")
    @ResponseWrapper(localName = "findUserForLoginResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindUserForLoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.heima.express.manage.client.Users findUserForLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "addRright", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.AddRright")
    @ResponseWrapper(localName = "addRrightResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.AddRrightResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int addRright(
        @WebParam(name = "arg0", targetNamespace = "")
        com.heima.express.manage.client.Users arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findUsersByInput", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindUsersByInput")
    @ResponseWrapper(localName = "findUsersByInputResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.FindUsersByInputResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DataGridResult findUsersByInput(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.Integer arg2
    );

    @WebMethod
    @RequestWrapper(localName = "updateRright", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.UpdateRright")
    @ResponseWrapper(localName = "updateRrightResponse", targetNamespace = "http://service.manage.express.heima.com/", className = "com.heima.express.manage.client.UpdateRrightResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int updateRright(
        @WebParam(name = "arg0", targetNamespace = "")
        com.heima.express.manage.client.Users arg0
    );
}
